### ISSUE TITLE
Need help implementing this

### ISSUE THREAD

**Issue by NatuerlichWuff** [iamntz/wp-ninja-forms-current-page-field#1]
Hello,

I'm currently building a Website on Wordpress and I want to implement your code. How can I do this?

**Comment by iamntz** [comment]
@NatuerlichWuff unfortunately it's been _so_ long that I don't remember if this is for NF2 or NF3, so that would be the first thing I would check.

Other than that, you need to:

1. download the archive
2. extract it on wp-content/plugins
3. activate the plugin
4. the field should be available inside NF admin.

that's all.
